### ISSUE TITLE
Field lists have weird padding

### ISSUE THREAD

**Issue by FichteFoll** [rtfd/sphinx_rtd_theme#149]
Source:

```
.. class: Test
    .. method: test()
        :param int point: Point in the view whose scope the selector should be
                          matched against.
        :param str selector: A scope selector.
        :returns bool: Whether the selector matches or not.
```

Current css:

``` css
.rst-content table.field-list td {
    border: medium none;
    padding-top: 5px;
}
```

![2014-09-16_17 37 14](https://cloud.githubusercontent.com/assets/931051/4289902/8c42de40-3db7-11e4-9c7f-3f75957894c2.png)

Without padding:

``` css
.rst-content table.field-list td {
    border: medium none;
}
```

![2014-09-16_17 37 28](https://cloud.githubusercontent.com/assets/931051/4289953/daef021c-3db7-11e4-8146-cae04e143c46.png)
