### ISSUE TITLE
Bullet lists inside enumerated lists are broken, except Arabic

### ISSUE THREAD

**Issue by TBBle** [rtfd/sphinx_rtd_theme#484]
Issue #118 fixed bullet lists inside enumerated lists when they are using arabic numbers, but the other forms of list numbering have the same issue.

Given:
```rst
Demonstration of nesting bullet lists inside enumerated lists
=============================================================

For reference, see `Bullet Lists`_ and `Enumerated Lists`_.

* A bullet list

  * A nested bullet list

#. An auto-numbered list

   * A nested bullet list

1. An explicity-arabic list

   * A nested bullet list

A. An explicity-uppercase alphabet list

   * A nested bullet list ==> **It has uppercase alphabet**

a. An explicity-lowercase alphabet list

   * A nested bullet list ==> **It has lowercase alphabet**

I. An explicity-uppercase roman list ==> **It has arabic**

   * A nested bullet list

i. An explicity-lowercase roman list ==> **It has arabic**

   * A nested bullet list

.. _Bullet Lists: http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#bullet-lists
.. _Enumerated Lists: http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#enumerated-lists
```

As noted, the fourth and fifth nested bullet lists get their parent list-style instead of their own list-style.

The bug appears to be that the fix applied in #118 (54a48b1) only applied changes to the `ol.arabic` rules in theme.css, not the `ol.loweralpha` and `ol.upperalpha` rules.

Also shown in this repro-case, Roman (upper and lower) lists don't get styled, and they also don't suffer the bug.

Rather than trying to match rules by `ol ul li` and `ul ol li` etc, would it make sense to give `ul` a class of their own, and then match *that* to style the `li` contained within? I guess that is a Sphinx issue rather than a theme issue though?

**Comment by TBBle** [comment]
As a local workaround, I added the following to some custom CSS, based on the fix to #118
```css
.rst-content ol.loweralpha li ul{margin-bottom:0 !important}
.rst-content ol.loweralpha li ul li{list-style:disc !important}
.rst-content ol.upperalpha li ul{margin-bottom:0 !important}
.rst-content ol.upperalpha li ul li{list-style:disc !important}
```
