### ISSUE TITLE
Positioning Previous button in footer

### ISSUE THREAD

**Issue by jfgossage** [rtfd/sphinx_rtd_theme#621]
### Problem

I have a project that supplies an extrafooter block. It uses super() to invoke the base block before itself.
### Reproducible Project

Please give a link to a public reproducible project or provide an example of the Restructured Text that gives an issue.

```html
{% extends '!footer.html' %} {% block extrafooter %}
 {{ super() }}
  <div id="cca">
 <br /> <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">
 <img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" /></a></div><br />
 <p>
 This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0 International License</a>
</p>
{% endblock %}
```

```css
/* Centers the Creative Commons Logo */
#cca {
	display: block;
	margin-left: 44%;
	margin_right: auto;
	width: 12%;
}

.txtc {
	text-align: center;
}

footer {
	text-align: center;
}
```

#### Error Logs/Results

Place any images or error logs that might be able to help solve the issue here.

#### Expected Results

The entire footer should have it's text centered. This is happening. However on pages that display the `Previous` button, the button is centered. It would look much better if it was left justified. I have found no way to do this without modifying the base theme which I would much prefer to avoid. An non-breaking enhancement that would fix this problem would be to add `float: left` to the CSS for the `Previous` button.

### Environment Info

- Python Version: 3.6.5
- Sphinx Version: current installed with pip
- RTD Theme Version: current installed with pip
